name: transmission-daemon-backend
version: '2.94'
base: core18
icon: files/logo.png
summary: Lightweight BitTorrent client (daemon backend)
grade: stable
# architectures: [armhf, amd64]
confinement: strict
description: |
  Transmission is a set of lightweight BitTorrent clients (in GUI, CLI
  and daemon form). All its incarnations feature a very simple, intuitive
  interface on top on an efficient, cross-platform back-ends. 
  This snap only contains the transmission-daemon back-end.

apps:
  # Configure daemon
  transmission-daemon:
    command: usr/bin/transmission-daemon -x $SNAP_COMMON/pid -g $SNAP_COMMON/.config -f
    post-stop-command: usr/bin/update-config
    daemon: simple
    plugs: [network, network-bind, removable-media, mount-observe]
    environment:
      TRANSMISSION_WEB_HOME: $SNAP/usr/share/transmission/web/

parts:
  # Install required packages.
  transmission-daemon:
    plugin: autotools
    source: https://github.com/transmission/transmission.git
    source-type: git
    source-branch: 2.9x
    source-depth: 1
    configflags:
      - --prefix=/
      - --enable-daemon
      - --disable-cli
      - --disable-lightweight
      - --enable-utp
      - --enable-nls
    build-packages:
      - libnatpmp-dev
      - libxml2-dev
      - libcurl4-openssl-dev
      - libevent-dev
      - pkg-config
      - zlib1g-dev
      - libssl-dev
      - libminiupnpc-dev
      - intltool

    stage-packages:
      - libnatpmp1
      - libcurl4
      - libevent-2.1-6
      - zlib1g
      - libminiupnpc10

    stage:
      # Omiting directories
      - -etc/transmission-daemon/
      - -var/lib/transmission-daemon/
      - -usr/share/doc/
      - -usr/share/man
      - -usr/share/icons

  # Copy default config and update config script, install hook copy configuration file into writable config dir
  custom-config:
    source: files/
    plugin: dump
    organize:
       settings.json: etc/transmission-daemon/settings.json
       update-config: usr/bin/update-config

# Permissions for hooks
hooks:
  install:
    plugs: [network, network-bind]
  configure:
    plugs: [network, network-bind]
