#!/bin/sh

# Moving config file to writable dir
CONFIG_FILE=$SNAP_COMMON/.config/settings.json
mkdir -p $SNAP_COMMON/.config
cp $SNAP/etc/transmission-daemon/settings.json $SNAP_COMMON/.config/settings.json

# Register config values with snapctl
for opt in `egrep -v '{|}' "$CONFIG_FILE" | sed 's^[ ",]^^g;s^:^=^'`; do
    snapctl set $opt
done
